data:extend({
    {
        type = "string-setting",
        name = "alert-visibilty-collector-path-blocked",
        order = "aa",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-custom",
        order = "ab",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-entity-destroyed",
        order = "ac",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-entity-under-attack",
        order = "ad",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-no-material-for-construction",
        order = "ae",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-no-platform-storage",
        order = "af",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-no-roboport-storage",
        order = "ag",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-no-storage",
        order = "ah",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-not-enough-construction-robots",
        order = "ai",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-not-enough-repair-packs",
        order = "aj",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-pipeline-overextended",
        order = "ak",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-platform-tile-building-blocked",
        order = "al",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-train-no-path",
        order = "am",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-train-out-of-fuel",
        order = "an",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-turret-fire",
        order = "ao",
        setting_type = "runtime-per-user",
        default_value = "Disabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-turret-out-of-ammo",
        order = "ap",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
    {
        type = "string-setting",
        name = "alert-visibilty-unclaimed-cargo",
        order = "aq",
        setting_type = "runtime-per-user",
        default_value = "Enabled",
        allowed_values = { "Enabled", "Muted", "Disabled" },
    },
})
